
services:
  - type: web
    plan: free
    name: RenameSnowProBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/oshadaX-Wolf/tiktok-tele-bot.git
    branch: main
    autoDeploy: false
    
